-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.0
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

select 1;

select *
FROM test02 t2
LEFT OUTER JOIN test01 t1 ON (t2.id = t1.id);

select *
FROM test01 t1
LEFT OUTER JOIN test02 t2 ON (t1.id = t2.id);
